

name: Azure CI Dev

env:
  AZURE_WEBAPP_NAME: goa-wdp-keycloak-proxy-dev   # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '	7.0.*'                 # set this to the .NET Core version to use

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: dotnet build webapi/webapi.csproj
